### ISSUE TITLE
Cannot handle namespaced tables

### ISSUE THREAD

**Issue by kuahyeow** [fluxfederation/partial_ks#11]
Snippet from the stacktrace :

```
    from /Users/kuahyeow/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/partial_ks-0.2.0/lib/partial_ks/table.rb:53:in `block in non_nullable_reflections'
    from /Users/kuahyeow/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/partial_ks-0.2.0/lib/partial_ks/table.rb:52:in `reject'
    from /Users/kuahyeow/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/partial_ks-0.2.0/lib/partial_ks/table.rb:52:in `non_nullable_reflections'
    from /Users/kuahyeow/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/partial_ks-0.2.0/lib/partial_ks/table.rb:23:in `candidate_parent_classes'
    from /Users/kuahyeow/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/partial_ks-0.2.0/lib/partial_ks/table.rb:17:in `top_level_table?'
```

**Comment by kuahyeow** [comment]
`Mysql2::Error: Table 'my_db.namespace_table' doesn't exist`. OK, so it looks like it can handle namespaced tables after all. Just have an issue with syncing the master version of the code vs older version of the database
